data:
  DPLAT_OW_SERVER: "10.134.9.37"
  ORACLECFG1: "OWEARTH 10.134.9.37 1521 OWEARTH"
  ORACLE_SID: "OWEARTH"
  LM_LICENSE_FILE: "2013@52.45.231.227"
  DB_USER: "centos"
  DB_USER_PWD: "centos"
  DISTRICT: "OWEARTH"
  OWDIRDATCFG1: "/d01/Landmark/OpenWorks OW_PROJ_DATA"
  DIRDATCFG1: "/d01/OWDATA/data/OWEARTH/seisdata OTHER_FILES"
  DISTRICTDATCFG1: "OWEARTH /d01/owconfig &quot;OWEARTH&quot; OWEARTH"
